export const COUNTRY_CODE_MAP: Record<string, string> = {
  // Asia - East & Southeast
  thailand: 'th',
  thai: 'th',
  ไทย: 'th',
  ประเทศไทย: 'th',
  'สยาม': 'th',
  siam: 'th',
  japan: 'jp',
  japanese: 'jp',
  nippon: 'jp',
  nihon: 'jp',
  ญี่ปุ่น: 'jp',
  'south korea': 'kr',
  'republic of korea': 'kr',
  korea: 'kr',
  korean: 'kr',
  เกาหลี: 'kr',
  เกาหลีใต้: 'kr',
  'north korea': 'kp',
  'dprk': 'kp',
  เกาหลีเหนือ: 'kp',
  china: 'cn',
  chinese: 'cn',
  prc: 'cn',
  จีน: 'cn',
  'สาธารณรัฐประชาชนจีน': 'cn',
  taiwan: 'tw',
  taiwanese: 'tw',
  roc: 'tw',
  ไต้หวัน: 'tw',
  'hong kong': 'hk',
  hongkong: 'hk',
  ฮ่องกง: 'hk',
  macau: 'mo',
  macao: 'mo',
  มาเก๊า: 'mo',
  singapore: 'sg',
  singaporean: 'sg',
  สิงคโปร์: 'sg',
  malaysia: 'my',
  malaysian: 'my',
  มาเลเซีย: 'my',
  vietnam: 'vn',
  vietnamese: 'vn',
  เวียดนาม: 'vn',
  indonesia: 'id',
  indonesian: 'id',
  อินโดนีเซีย: 'id',
  philippines: 'ph',
  filipino: 'ph',
  philippine: 'ph',
  ฟิลิปปินส์: 'ph',
  myanmar: 'mm',
  burma: 'mm',
  burmese: 'mm',
  พม่า: 'mm',
  เมียนมา: 'mm',
  เมียนมาร์: 'mm',
  cambodia: 'kh',
  cambodian: 'kh',
  กัมพูชา: 'kh',
  เขมร: 'kh',
  laos: 'la',
  laotian: 'la',
  lao: 'la',
  ลาว: 'la',
  brunei: 'bn',
  บรูไน: 'bn',
  'timor-leste': 'tl',
  'east timor': 'tl',
  'ติมอร์-เลสเต': 'tl',
  'ติมอร์ตะวันออก': 'tl',
  mongolia: 'mn',
  mongolian: 'mn',
  มองโกเลีย: 'mn',

  // Asia - South & Central
  india: 'in',
  indian: 'in',
  bharat: 'in',
  อินเดีย: 'in',
  pakistan: 'pk',
  pakistani: 'pk',
  ปากีสถาน: 'pk',
  bangladesh: 'bd',
  bangladeshi: 'bd',
  บังกลาเทศ: 'bd',
  'sri lanka': 'lk',
  'sri lankan': 'lk',
  ceylon: 'lk',
  ศรีลังกา: 'lk',
  nepal: 'np',
  nepalese: 'np',
  nepali: 'np',
  เนปาล: 'np',
  bhutan: 'bt',
  bhutanese: 'bt',
  ภูฏาน: 'bt',
  maldives: 'mv',
  maldivian: 'mv',
  มัลดีฟส์: 'mv',
  afghanistan: 'af',
  afghan: 'af',
  อัฟกานิสถาน: 'af',
  kazakhstan: 'kz',
  kazakh: 'kz',
  คาซัคสถาน: 'kz',
  uzbekistan: 'uz',
  uzbek: 'uz',
  อุซเบกิสถาน: 'uz',
  turkmenistan: 'tm',
  turkmen: 'tm',
  เติร์กเมนิสถาน: 'tm',
  kyrgyzstan: 'kg',
  kyrgyz: 'kg',
  คีร์กีซสถาน: 'kg',
  tajikistan: 'tj',
  tajik: 'tj',
  ทาจิกิสถาน: 'tj',

  // Middle East & West Asia
  'united arab emirates': 'ae',
  uae: 'ae',
  emirates: 'ae',
  emirati: 'ae',
  'dubai': 'ae',
  'abu dhabi': 'ae',
  ดูไบ: 'ae',
  สหรัฐอาหรับเอมิเรตส์: 'ae',
  'saudi arabia': 'sa',
  saudi: 'sa',
  ซาอุดีอาระเบีย: 'sa',
  ซาอุ: 'sa',
  israel: 'il',
  israeli: 'il',
  อิสราเอล: 'il',
  palestine: 'ps',
  palestinian: 'ps',
  ปาเลสไตน์: 'ps',
  turkey: 'tr',
  turkiye: 'tr',
  'türkiye': 'tr',
  turkish: 'tr',
  ตุรกี: 'tr',
  ทูร์เคีย: 'tr',
  syria: 'sy',
  syrian: 'sy',
  ซีเรีย: 'sy',
  iran: 'ir',
  iranian: 'ir',
  persia: 'ir',
  persian: 'ir',
  อิหร่าน: 'ir',
  iraq: 'iq',
  iraqi: 'iq',
  อิรัก: 'iq',
  qatar: 'qa',
  qatari: 'qa',
  กาตาร์: 'qa',
  kuwait: 'kw',
  kuwaiti: 'kw',
  คูเวต: 'kw',
  bahrain: 'bh',
  bahraini: 'bh',
  บาห์เรน: 'bh',
  oman: 'om',
  omani: 'om',
  โอมาน: 'om',
  yemen: 'ye',
  yemeni: 'ye',
  เยเมน: 'ye',
  jordan: 'jo',
  jordanian: 'jo',
  จอร์แดน: 'jo',
  lebanon: 'lb',
  lebanese: 'lb',
  เลบานอน: 'lb',
  armenia: 'am',
  armenian: 'am',
  อาร์เมเนีย: 'am',
  azerbaijan: 'az',
  azerbaijani: 'az',
  อาเซอร์ไบจาน: 'az',
  georgia: 'ge',
  georgian: 'ge',
  จอร์เจีย: 'ge',
  cyprus: 'cy',
  cypriot: 'cy',
  ไซปรัส: 'cy',

  // Europe - Western & Northern
  'united kingdom': 'gb',
  uk: 'gb',
  'great britain': 'gb',
  britain: 'gb',
  british: 'gb',
  england: 'gb',
  english: 'gb',
  scotland: 'gb',
  scottish: 'gb',
  wales: 'gb',
  welsh: 'gb',
  'northern ireland': 'gb',
  อังกฤษ: 'gb',
  สหราชอาณาจักร: 'gb',
  บริเตน: 'gb',
  france: 'fr',
  french: 'fr',
  française: 'fr',
  ฝรั่งเศส: 'fr',
  germany: 'de',
  german: 'de',
  deutschland: 'de',
  deutsch: 'de',
  เยอรมนี: 'de',
  เยอรมัน: 'de',
  italy: 'it',
  italian: 'it',
  italia: 'it',
  italiano: 'it',
  อิตาลี: 'it',
  spain: 'es',
  spanish: 'es',
  españa: 'es',
  espanol: 'es',
  español: 'es',
  สเปน: 'es',
  portugal: 'pt',
  portuguese: 'pt',
  português: 'pt',
  โปรตุเกส: 'pt',
  netherlands: 'nl',
  dutch: 'nl',
  holland: 'nl',
  nederland: 'nl',
  เนเธอร์แลนด์: 'nl',
  ฮอลแลนด์: 'nl',
  belgium: 'be',
  belgian: 'be',
  belgique: 'be',
  belgië: 'be',
  เบลเยียม: 'be',
  switzerland: 'ch',
  swiss: 'ch',
  schweiz: 'ch',
  suisse: 'ch',
  svizzera: 'ch',
  สวิตเซอร์แลนด์: 'ch',
  สวิส: 'ch',
  austria: 'at',
  austrian: 'at',
  'österreich': 'at',
  oesterreich: 'at',
  ออสเตรีย: 'at',
  sweden: 'se',
  swedish: 'se',
  sverige: 'se',
  svenska: 'se',
  สวีเดน: 'se',
  norway: 'no',
  norwegian: 'no',
  norge: 'no',
  norsk: 'no',
  นอร์เวย์: 'no',
  denmark: 'dk',
  danish: 'dk',
  danmark: 'dk',
  dansk: 'dk',
  เดนมาร์ก: 'dk',
  finland: 'fi',
  finnish: 'fi',
  suomi: 'fi',
  ฟินแลนด์: 'fi',
  iceland: 'is',
  icelandic: 'is',
  ísland: 'is',
  ไอซ์แลนด์: 'is',
  ireland: 'ie',
  irish: 'ie',
  éire: 'ie',
  ไอร์แลนด์: 'ie',
  greece: 'gr',
  greek: 'gr',
  hellas: 'gr',
  ellada: 'gr',
  กรีซ: 'gr',
  luxembourg: 'lu',
  luxembourgish: 'lu',
  ลักเซมเบิร์ก: 'lu',
  monaco: 'mc',
  monegasque: 'mc',
  โมนาโก: 'mc',
  liechtenstein: 'li',
  ลิกเตนสไตน์: 'li',
  andorra: 'ad',
  อันดอร์รา: 'ad',
  'san marino': 'sm',
  ซานมารีโน: 'sm',
  vatican: 'va',
  'holy see': 'va',
  วาติกัน: 'va',
  malta: 'mt',
  maltese: 'mt',
  มอลตา: 'mt',

  // Europe - Central & Eastern
  poland: 'pl',
  polish: 'pl',
  polska: 'pl',
  polski: 'pl',
  โปแลนด์: 'pl',
  'czech republic': 'cz',
  czechia: 'cz',
  czech: 'cz',
  'česká republika': 'cz',
  เช็ก: 'cz',
  slovakia: 'sk',
  slovak: 'sk',
  slovensko: 'sk',
  สโลวาเกีย: 'sk',
  hungary: 'hu',
  hungarian: 'hu',
  magyarország: 'hu',
  magyar: 'hu',
  ฮังการี: 'hu',
  romania: 'ro',
  romanian: 'ro',
  românia: 'ro',
  โรมาเนีย: 'ro',
  bulgaria: 'bg',
  bulgarian: 'bg',
  บัลแกเรีย: 'bg',
  serbia: 'rs',
  serbian: 'rs',
  srbija: 'rs',
  เซอร์เบีย: 'rs',
  croatia: 'hr',
  croatian: 'hr',
  hrvatska: 'hr',
  โครเอเชีย: 'hr',
  slovenia: 'si',
  slovenian: 'si',
  slovenija: 'si',
  สโลวีเนีย: 'si',
  'bosnia and herzegovina': 'ba',
  bosnia: 'ba',
  herzegovina: 'ba',
  bosnian: 'ba',
  บอสเนีย: 'ba',
  'บอสเนียและเฮอร์เซโกวีนา': 'ba',
  montenegro: 'me',
  'crna gora': 'me',
  มอนเตเนโกร: 'me',
  'north macedonia': 'mk',
  macedonia: 'mk',
  macedonian: 'mk',
  มาซิโดเนีย: 'mk',
  'นอร์ทมาซิโดเนีย': 'mk',
  albania: 'al',
  albanian: 'al',
  shqipëria: 'al',
  แอลเบเนีย: 'al',
  kosovo: 'xk',
  kosovar: 'xk',
  โคโซโว: 'xk',
  ukraine: 'ua',
  ukrainian: 'ua',
  ukrayina: 'ua',
  ยูเครน: 'ua',
  russia: 'ru',
  russian: 'ru',
  rossiya: 'ru',
  รัสเซีย: 'ru',
  belarus: 'by',
  belarusian: 'by',
  เบลารุส: 'by',
  estonia: 'ee',
  estonian: 'ee',
  eesti: 'ee',
  เอสโตเนีย: 'ee',
  latvia: 'lv',
  latvian: 'lv',
  latvija: 'lv',
  ลัตเวีย: 'lv',
  lithuania: 'lt',
  lithuanian: 'lt',
  lietuva: 'lt',
  ลิทัวเนีย: 'lt',
  moldova: 'md',
  moldovan: 'md',
  มอลโดวา: 'md',

  // Americas - North, Central, South & Caribbean
  'united states': 'us',
  'united states of america': 'us',
  usa: 'us',
  america: 'us',
  american: 'us',
  'u.s.': 'us',
  'u.s.a.': 'us',
  สหรัฐอเมริกา: 'us',
  สหรัฐ: 'us',
  อเมริกา: 'us',
  canada: 'ca',
  canadian: 'ca',
  แคนาดา: 'ca',
  mexico: 'mx',
  mexican: 'mx',
  'méxico': 'mx',
  mejico: 'mx',
  เม็กซิโก: 'mx',
  brazil: 'br',
  brasil: 'br',
  brazilian: 'br',
  brasileiro: 'br',
  บราซิล: 'br',
  argentina: 'ar',
  argentine: 'ar',
  argentinian: 'ar',
  อาร์เจนตินา: 'ar',
  chile: 'cl',
  chilean: 'cl',
  ชิลี: 'cl',
  colombia: 'co',
  colombian: 'co',
  โคลอมเบีย: 'co',
  peru: 'pe',
  peruvian: 'pe',
  perú: 'pe',
  เปรู: 'pe',
  venezuela: 've',
  venezuelan: 've',
  เวเนซุเอลา: 've',
  ecuador: 'ec',
  ecuadorian: 'ec',
  เอกวาดอร์: 'ec',
  bolivia: 'bo',
  bolivian: 'bo',
  โบลิเวีย: 'bo',
  paraguay: 'py',
  paraguayan: 'py',
  ปารากวัย: 'py',
  uruguay: 'uy',
  uruguayan: 'uy',
  อุรุกวัย: 'uy',
  cuba: 'cu',
  cuban: 'cu',
  คิวบา: 'cu',
  'dominican republic': 'do',
  dominican: 'do',
  'สาธารณรัฐโดมินิกัน': 'do',
  'puerto rico': 'pr',
  'puerto rican': 'pr',
  เปอร์โตริโก: 'pr',
  panama: 'pa',
  panamanian: 'pa',
  panamá: 'pa',
  ปานามา: 'pa',
  'costa rica': 'cr',
  'costa rican': 'cr',
  คอสตาริกา: 'cr',
  guatemala: 'gt',
  guatemalan: 'gt',
  กัวเตมาลา: 'gt',
  honduras: 'hn',
  honduran: 'hn',
  ฮอนดูรัส: 'hn',
  'el salvador': 'sv',
  salvadoran: 'sv',
  เอลซัลวาดอร์: 'sv',
  nicaragua: 'ni',
  nicaraguan: 'ni',
  นิการากัว: 'ni',
  jamaica: 'jm',
  jamaican: 'jm',
  จาเมกา: 'jm',
  haiti: 'ht',
  haitian: 'ht',
  เฮติ: 'ht',
  bahamas: 'bs',
  bahamian: 'bs',
  บาฮามาส: 'bs',
  barbados: 'bb',
  barbadian: 'bb',
  บาร์เบโดส: 'bb',
  'trinidad and tobago': 'tt',
  trinidad: 'tt',
  tobago: 'tt',
  'ตรินิแดดและโตเบโก': 'tt',
  guyana: 'gy',
  guyanese: 'gy',
  กายอานา: 'gy',
  suriname: 'sr',
  surinamese: 'sr',
  ซูรินาเม: 'sr',
  belize: 'bz',
  belizean: 'bz',
  เบลีซ: 'bz',

  // Oceania & Pacific
  australia: 'au',
  australian: 'au',
  aussie: 'au',
  ออสเตรเลีย: 'au',
  'new zealand': 'nz',
  'new zealander': 'nz',
  kiwi: 'nz',
  aotearoa: 'nz',
  นิวซีแลนด์: 'nz',
  fiji: 'fj',
  fijian: 'fj',
  ฟิจิ: 'fj',
  'papua new guinea': 'pg',
  png: 'pg',
  'ปาปัวนิวกินี': 'pg',
  'solomon islands': 'sb',
  'หมู่เกาะโซโลมอน': 'sb',
  vanuatu: 'vu',
  วานูอาตู: 'vu',
  samoa: 'ws',
  samoan: 'ws',
  ซามัว: 'ws',
  tonga: 'to',
  tongan: 'to',
  ตองกา: 'to',
  guam: 'gu',
  กวม: 'gu',
  tahiti: 'pf',
  'french polynesia': 'pf',
  'เฟรนช์โปลินีเซีย': 'pf',
  'new caledonia': 'nc',
  'นิวแคลิโดเนีย': 'nc',

  // Africa
  egypt: 'eg',
  egyptian: 'eg',
  misr: 'eg',
  อียิปต์: 'eg',
  'south africa': 'za',
  'south african': 'za',
  แอฟริกาใต้: 'za',
  morocco: 'ma',
  moroccan: 'ma',
  maroc: 'ma',
  โมร็อกโก: 'ma',
  algeria: 'dz',
  algerian: 'dz',
  แอลจีเรีย: 'dz',
  tunisia: 'tn',
  tunisian: 'tn',
  ตูนิเซีย: 'tn',
  libya: 'ly',
  libyan: 'ly',
  ลิเบีย: 'ly',
  sudan: 'sd',
  sudanese: 'sd',
  ซูดาน: 'sd',
  'south sudan': 'ss',
  ซูดานใต้: 'ss',
  ethiopia: 'et',
  ethiopian: 'et',
  เอธิโอเปีย: 'et',
  kenya: 'ke',
  kenyan: 'ke',
  เคนยา: 'ke',
  nigeria: 'ng',
  nigerian: 'ng',
  ไนจีเรีย: 'ng',
  ghana: 'gh',
  ghanaian: 'gh',
  กานา: 'gh',
  tanzania: 'tz',
  tanzanian: 'tz',
  แทนซาเนีย: 'tz',
  uganda: 'ug',
  ugandan: 'ug',
  ยูกันดา: 'ug',
  angola: 'ao',
  angolan: 'ao',
  แองโกลา: 'ao',
  mozambique: 'mz',
  โมซัมบิก: 'mz',
  zimbabwe: 'zw',
  ซิมบับเว: 'zw',
  zambia: 'zm',
  แซมเบีย: 'zm',
  madagascar: 'mg',
  มาดากัสการ์: 'mg',
  mauritius: 'mu',
  มอริเชียส: 'mu',
  seychelles: 'sc',
  เซเชลส์: 'sc',
  rwanda: 'rw',
  รวันดา: 'rw',
  senegal: 'sn',
  เซเนกัล: 'sn',
  "cote d'ivoire": 'ci',
  'ivory coast': 'ci',
  'ไอวอรีโคสต์': 'ci',
  'โกตดิวัวร์': 'ci',
  cameroon: 'cm',
  แคเมอรูน: 'cm',
  'dr congo': 'cd',
  'congo dr': 'cd',
  'democratic republic of the congo': 'cd',
  'สาธารณรัฐประชาธิปไตยคองโก': 'cd',
  congo: 'cg',
  คองโก: 'cg',
  somalia: 'so',
  โซมาเลีย: 'so',
  mali: 'ml',
  มาลี: 'ml',
  'burkina faso': 'bf',
  บูร์กินาฟาโซ: 'bf',
  guinea: 'gn',
  กินี: 'gn',
  benin: 'bj',
  เบนิน: 'bj',
  togo: 'tg',
  โตโก: 'tg',
  'sierra leone': 'sl',
  เซียร์ราลีโอน: 'sl',
  liberia: 'lr',
  ไลบีเรีย: 'lr',
  namibia: 'na',
  นามิเบีย: 'na',
  botswana: 'bw',
  บอตสวานา: 'bw',
  gabon: 'ga',
  กาบอง: 'ga',
  eswatini: 'sz',
  swaziland: 'sz',
  เอสวาตินี: 'sz',
  สวาซิแลนด์: 'sz',
  lesotho: 'ls',
  เลโซโท: 'ls',
  'cape verde': 'cv',
  'cabo verde': 'cv',
  กาบูเวร์ดี: 'cv',
  malawi: 'mw',
  มาลาวี: 'mw',
  burundi: 'bi',
  บุรุนดี: 'bi',
  chad: 'td',
  ชาด: 'td',
  niger: 'ne',
  ไนเจอร์: 'ne',

  // Cultural / Autonomous regions
  kurdistan: 'krd',
  kurdish: 'krd',
  kurd: 'krd',
  kurdistani: 'krd',
  เคอร์ดิสถาน: 'krd',
  เคิร์ด: 'krd',
  tibet: 'tibet',
  tibetan: 'tibet',
  ทิเบต: 'tibet',
  ธิเบต: 'tibet',
};

/**
 * 3-Letter ISO-3166-1 alpha-3 to 2-Letter ISO-3166-1 alpha-2 Code Map
 * Covering all official 249 ISO codes
 */
export const ISO3_TO_ISO2: Record<string, string> = {
  tha: 'th',
  jpn: 'jp',
  kor: 'kr',
  prk: 'kp',
  chn: 'cn',
  twn: 'tw',
  hkg: 'hk',
  mac: 'mo',
  sgp: 'sg',
  mys: 'my',
  idn: 'id',
  phl: 'ph',
  vnm: 'vn',
  mmr: 'mm',
  khm: 'kh',
  lao: 'la',
  brn: 'bn',
  tls: 'tl',
  ind: 'in',
  pak: 'pk',
  bgd: 'bd',
  lka: 'lk',
  npl: 'np',
  btn: 'bt',
  mdv: 'mv',
  afg: 'af',
  mng: 'mn',
  kaz: 'kz',
  uzb: 'uz',
  tkm: 'tm',
  kgz: 'kg',
  tjk: 'tj',
  gbr: 'gb',
  fra: 'fr',
  deu: 'de',
  ita: 'it',
  esp: 'es',
  prt: 'pt',
  nld: 'nl',
  bel: 'be',
  che: 'ch',
  aut: 'at',
  swe: 'se',
  nor: 'no',
  dnk: 'dk',
  fin: 'fi',
  isl: 'is',
  irl: 'ie',
  grc: 'gr',
  pol: 'pl',
  cze: 'cz',
  svk: 'sk',
  hun: 'hu',
  rou: 'ro',
  bgr: 'bg',
  srb: 'rs',
  hrv: 'hr',
  svn: 'si',
  bih: 'ba',
  mne: 'me',
  mkd: 'mk',
  alb: 'al',
  ukr: 'ua',
  rus: 'ru',
  blr: 'by',
  est: 'ee',
  lva: 'lv',
  ltu: 'lt',
  cyp: 'cy',
  mlt: 'mt',
  lux: 'lu',
  mda: 'md',
  geo: 'ge',
  arm: 'am',
  aze: 'az',
  tur: 'tr',
  sau: 'sa',
  are: 'ae',
  qat: 'qa',
  kwt: 'kw',
  bhr: 'bh',
  omn: 'om',
  yem: 'ye',
  isr: 'il',
  pse: 'ps',
  jor: 'jo',
  lbn: 'lb',
  syr: 'sy',
  irq: 'iq',
  irn: 'ir',
  usa: 'us',
  can: 'ca',
  mex: 'mx',
  bra: 'br',
  arg: 'ar',
  chl: 'cl',
  col: 'co',
  per: 'pe',
  ven: 've',
  ecu: 'ec',
  bol: 'bo',
  pry: 'py',
  ury: 'uy',
  cub: 'cu',
  dom: 'do',
  pri: 'pr',
  pan: 'pa',
  cri: 'cr',
  gtm: 'gt',
  hnd: 'hn',
  slv: 'sv',
  nic: 'ni',
  jam: 'jm',
  hti: 'ht',
  bhs: 'bs',
  brb: 'bb',
  tto: 'tt',
  guy: 'gy',
  sur: 'sr',
  blz: 'bz',
  aus: 'au',
  nzl: 'nz',
  fji: 'fj',
  png: 'pg',
  slb: 'sb',
  vut: 'vu',
  wsm: 'ws',
  ton: 'to',
  gum: 'gu',
  pyf: 'pf',
  ncl: 'nc',
  egy: 'eg',
  zaf: 'za',
  mar: 'ma',
  dza: 'dz',
  tun: 'tn',
  lby: 'ly',
  sdn: 'sd',
  ssd: 'ss',
  eth: 'et',
  ken: 'ke',
  nga: 'ng',
  gha: 'gh',
  tza: 'tz',
  uga: 'ug',
  ago: 'ao',
  moz: 'mz',
  zwe: 'zw',
  zmb: 'zm',
  mdg: 'mg',
  mus: 'mu',
  syc: 'sc',
  rwa: 'rw',
  sen: 'sn',
  civ: 'ci',
  cmr: 'cm',
  cod: 'cd',
  cog: 'cg',
  som: 'so',
  mli: 'ml',
  bfa: 'bf',
  gin: 'gn',
  ben: 'bj',
  tgo: 'tg',
  sle: 'sl',
  lbr: 'lr',
  nam: 'na',
  bwa: 'bw',
  gab: 'ga',
  gnq: 'gq',
  swz: 'sz',
  lso: 'ls',
  cpv: 'cv',
  com: 'km',
  dji: 'dj',
  eri: 'er',
  gmb: 'gm',
  gnb: 'gw',
  mrt: 'mr',
  stp: 'st',
  mwi: 'mw',
  bdi: 'bi',
  caf: 'cf',
  tcd: 'td',
  ner: 'ne',
};

/**
 * Custom High-Resolution Flag Image URLs for Autonomous / Cultural Regions
 */
export const CUSTOM_FLAG_URLS: Record<string, string> = {
  krd: '/flags/kurdistan.svg',
  kurdistan: '/flags/kurdistan.svg',
  kurdish: '/flags/kurdistan.svg',
  'เคอร์ดิสถาน': '/flags/kurdistan.svg',
  'เคิร์ด': '/flags/kurdistan.svg',
  kurdistani: '/flags/kurdistan.svg',
  kurd: '/flags/kurdistan.svg',
  tibet: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Flag_of_Tibet.svg/160px-Flag_of_Tibet.svg.png',
  'ทิเบต': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Flag_of_Tibet.svg/160px-Flag_of_Tibet.svg.png',
  'ธิเบต': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Flag_of_Tibet.svg/160px-Flag_of_Tibet.svg.png',
};

/**
 * Resolves a country string to a 2-letter ISO code for FlagCDN
 */
export function getCountryCode(countryName?: string | null): string {
  if (!countryName) return '';
  const clean = countryName.toLowerCase().trim();
  if (!clean) return '';

  // 1. Direct 2-letter ISO code match (e.g. "th", "it", "jp", "us", "gb", "fr", "br")
  if (clean.length === 2 && /^[a-z]{2}$/.test(clean)) {
    return clean;
  }

  // 2. Direct exact dictionary match
  if (COUNTRY_CODE_MAP[clean]) {
    return COUNTRY_CODE_MAP[clean];
  }

  // 3. 3-letter ISO code match (e.g. "tha", "jpn", "usa", "gbr", "bra")
  if (ISO3_TO_ISO2[clean]) {
    return ISO3_TO_ISO2[clean];
  }

  // 4. Tokenize by space, comma, slash, hyphen and check each part
  const tokens = clean.split(/[\s,/\-]+/).filter((t) => t.length >= 2);
  for (const token of tokens) {
    if (token.length === 2 && /^[a-z]{2}$/.test(token)) {
      return token;
    }
    if (COUNTRY_CODE_MAP[token]) {
      return COUNTRY_CODE_MAP[token];
    }
    if (ISO3_TO_ISO2[token]) {
      return ISO3_TO_ISO2[token];
    }
  }

  // 5. Check whole-word / phrase match
  for (const [key, code] of Object.entries(COUNTRY_CODE_MAP)) {
    if (key.length >= 3) {
      if (
        clean === key ||
        clean.startsWith(key + ' ') ||
        clean.endsWith(' ' + key) ||
        clean.includes(' ' + key + ' ') ||
        clean.startsWith(key + ',')
      ) {
        return code;
      }
    }
  }

  // 6. Safe substring match for unique keys with length >= 4
  for (const [key, code] of Object.entries(COUNTRY_CODE_MAP)) {
    if (key.length >= 4 && clean.includes(key)) {
      return code;
    }
  }

  return '';
}

/**
 * Converts a country name to a Unicode emoji flag (e.g. "th" -> 🇹🇭)
 */
export function getCountryFlagEmoji(countryName?: string | null): string {
  const code = getCountryCode(countryName);
  if (!code) return '🌐';
  if (code === 'krd') return '☀️';
  if (code === 'tibet') return '🏔️';
  if (code.length !== 2) return '🌐';
  return String.fromCodePoint(...code.toUpperCase().split('').map((c) => 127397 + c.charCodeAt(0)));
}

/**
 * Returns Flag Image URL (e.g. https://flagcdn.com/w80/th.png or Custom Regional Flag URL)
 */
export function getFlagImageUrl(countryName?: string | null): string {
  if (!countryName) return '';
  const clean = countryName.trim().toLowerCase();

  // 1. Check custom direct regional flag URLs first (e.g. Kurdistan, Tibet)
  for (const [key, url] of Object.entries(CUSTOM_FLAG_URLS)) {
    if (clean === key || clean.includes(key)) {
      return url;
    }
  }

  const code = getCountryCode(countryName);
  if (!code) return '';

  if (CUSTOM_FLAG_URLS[code]) {
    return CUSTOM_FLAG_URLS[code];
  }

  return `https://flagcdn.com/w80/${code}.png`;
}
