name = "art-gallery"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "art-gallery-db"
database_id = "eb00adbe-499f-48b5-8c70-992cafca4967"
migrations_dir = "drizzle"

[vars]
NEXT_PUBLIC_SITE_URL = "https://art-gallery-4ty.pages.dev"
